### ISSUE TITLE
Invalid syntax in Ditto.swift

### ISSUE THREAD

**Issue by OlafAndreas** [dittowords/cli#106]
When doing a pull, for localized strings using multiple custom parameters, the generated syntax is invalid.

In the following example you can see that too many commas are being added in the signature and body of the function, creating invalid syntax. The last two parameters in the `localizedStringWithFormat(:_, ...)` seems to be concatenated, which also is wrong.

Expected result:

```
public static func infoDescription(_ localeOverride: String? = nil, userFullName: String, userAddress: String, deliveryDatePostalCode: String, deliveryDatePostalPlace: String, recipientName: String = "Mottaker") -> String {
			  String.localizedStringWithFormat(NSLocalizedString("infoDescription", tableName: "app", bundle: getBundle(localeOverride), comment: ""), userFullName, userAddress, deliveryDatePostalCode, deliveryDatePostalPlace, recipientName)
		}
```

Actual result:
```
public static func infoDescription(_ localeOverride: String? = nil, userFullName: String, , userAddress: String, , deliveryDatePostalCode: String, , deliveryDatePostalPlace: String, , recipientName: String = "Mottaker") -> String {  
			  String.localizedStringWithFormat(NSLocalizedString("infoDescription", tableName: "app", bundle: getBundle(localeOverride), comment: ""), userFullName, userAddress, deliveryDatePostalCode, deliveryDatePostalPlacerecipientName, )
		}
```

Config.yml
```
status: FINAL
sources:
  components: true
  projects:
    - id: [REDACTED]
      name: app
variants: true
format:
    - ios-strings
    - ios-stringsdict
iosLocales:
    - base: nb
    - danish: da
    - english: en
    - svenska: sv
      
```
